const SYSTEM_CONFIG = {
  platforms: [
    {
      url: 'https://chat.openai.com',
      loginUrls: [
        'https://auth0.openai.com',
        'https://accounts.google.com',
        'https://appleid.apple.com/auth/authorize',
        'https://login.live.com',
      ],
      loginPlaceholder: 'Login to ChatGPT above, then type anything below.',
      alias: 'gp',
      name: 'ChatGPT',
      color: '#2BA9B7',
      userAgent: 'desktop_windows',
      zoomLevel: 0.9,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 1000,
    },
    {
      url: 'https://claude.ai/chat',
      loginUrls: ['https://claude.ai/login', 'https://accounts.google.com'],
      loginPlaceholder: 'Login to Claude above, then type anything below.',
      alias: 'cl',
      name: 'Claude-2',
      color: '#D19B75',
      userAgent: 'desktop_windows',
      zoomLevel: 0.9,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 1000,
    },
    {
      url: 'https://www.bing.com/chat',
      loginUrls: [
        'https://login.live.com',
        'https://login.microsoft.com',
        'https://signup.live.com',
      ],
      loginPlaceholder: 'Login to Bing above, then type anything below.',
      alias: 'bi',
      name: 'Bing Chat',
      color: '#3769C8',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://bard.google.com',
      loginUrls: ['https://accounts.google.com'],
      loginPlaceholder: 'Login to Bard above, then type anything below.',
      alias: 'ba',
      name: 'Bard',
      color: '#FE7E43',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://poe.com/Assistant',
      loginUrls: [
        'https://poe.com/login',
        'https://accounts.google.com',
        'https://appleid.apple.com/auth/authorize',
      ],
      loginPlaceholder: 'Login to Poe above, then type anything below.',
      alias: 'po',
      name: 'Poe',
      color: '#8C71FF',
      userAgent: 'desktop_windows',
      zoomLevel: 0.9,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://beta.character.ai/chat?char=YntB_ZeqRq2l_aVf2gWDCZl4oBttQzDvhj9cXafWcF8',
      loginUrls: [
        'https://character-ai.us.auth0.com',
        'https://accounts.google.com',
        'https://www.facebook.com/login.php',
        'https://discord.com/login',
        'https://appleid.apple.com/auth/authorize',
      ],
      loginPlaceholder: 'Login to Character above, then type anything below.',
      chooseBotUrls: [/^https:\/\/beta.character.ai\/$/],
      chooseBotPlaceholder: 'Choose a Character bot, then type anything below.',
      alias: 'ch',
      name: 'Character.ai',
      color: '#D385F8',
      userAgent: 'desktop_windows',
      zoomLevel: 0.91,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://pi.ai/talk?scr',
      loginUrls: [
        'https://accounts.google.com',
        'https://www.facebook.com/login.php',
        'https://appleid.apple.com/auth/authorize',
      ],
      loginPlaceholder: 'Login to Pi above, then type anything below.',
      alias: 'pi',
      name: 'Pi',
      color: '#44B39D',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://huggingface.co/chat',
      loginUrls: [
        'https://huggingface.co/login',
        'https://huggingface.co/password_reset',
        'https://huggingface.co/join',
      ],
      loginPlaceholder: 'Login to Huggingface above, then type anything below.',
      alias: 'hu',
      name: 'Huggingchat',
      color: '#FFB827',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://www.perplexity.ai',
      loginUrls: [
        'https://accounts.google.com',
        'https://appleid.apple.com/auth/authorize',
        'https://www.perplexity.ai/api/auth/verify-request',
      ],
      loginPlaceholder: 'Login to Perplexity above, then type anything below.',
      alias: 'pe',
      name: 'Perplexity',
      color: '#000000',
      userAgent: '',
      zoomLevel: 1,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://google.com/ncr',
      loginUrls: ['https://accounts.google.com'],
      loginPlaceholder: 'Login to Google above, then type anything below.',
      alias: 'go',
      name: 'Google Search',
      color: '#41C564',
      userAgent: 'mobile_pixel',
      zoomLevel: 1,
      state: 'awake',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://images.google.com',
      loginUrls: [],
      loginPlaceholder: '',
      alias: 'gi',
      name: 'Google Images',
      color: '#F49C46',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'not_shown',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://maps.google.com',
      loginUrls: [],
      loginPlaceholder: '',
      alias: 'mp',
      name: 'Google Maps',
      color: '#057B89',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'not_shown',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://www.youtube.com',
      loginUrls: [],
      loginPlaceholder: '',
      alias: 'yt',
      name: 'Youtube',
      color: '#FC4343',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'not_shown',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://www.gmail.com',
      loginUrls: [],
      loginPlaceholder: '',
      alias: 'gm',
      name: 'Gmail',
      color: '#FC87B3',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'not_shown',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://www.calculator.net',
      loginUrls: [],
      loginPlaceholder: '',
      alias: 'ca',
      name: 'Calculator',
      color: '#96BEC4',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'not_shown',
      isPlatform: true,
      delayShowTime: 0,
    },
    {
      url: 'https://translate.google.com',
      loginUrls: [],
      loginPlaceholder: '',
      alias: 'tr',
      name: 'Google Translate',
      color: '#5C9AFF',
      userAgent: 'desktop_windows',
      zoomLevel: 1,
      state: 'not_shown',
      isPlatform: true,
      delayShowTime: 0,
    },
  ],
  localBasePlatform: {
    url: 'http://localhost:8000',
    loginUrls: [],
    loginPlaceholder: '',
    alias: 'local',
    name: 'Local Base',
    color: '#8C71FF',
    userAgent: 'desktop_windows',
    zoomLevel: 0.9,
    state: 'awake',
    isPlatform: false,
    delayShowTime: 0,
  },
  openInterpreterPlatform: {
    url: 'file://' + __dirname + '/q1Interpreter.html',
    loginUrls: [],
    loginPlaceholder: '',
    alias: 'interpreter',
    name: 'Open Interpreter',
    color: '#8C71FF',
    userAgent: 'desktop_windows',
    zoomLevel: 0.9,
    state: 'awake',
    isPlatform: false,
    delayShowTime: 0,
  },
  selectionActions: [
    {
      id: 'action1',
      text: 'Action Text 1',
    },
    {
      id: 'action2',
      text: 'Action Text 2',
    },
    {
      id: 'action3',
      text: 'Action Text 3',
    },
  ],
  maximizeEnabled: true,
  operationsEnabled: true,
  interpreterEnabled: true,
  textImportEnabled: true,
  screenshotToolEnabled: true,
  actionBarEnabled: true,
  noticePopupJsonUrl: 'https://qute-app.s3.amazonaws.com/popup.json',
  latestMajorJsonUrl: 'https://qute-app.s3.amazonaws.com/latest-major.json',
  defaultCustomUrlTab: { userAgent: 'desktop_windows', zoomLevel: 1 },
  userAgentMeta: {
    desktop_windows:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
    mobile_pixel:
      'Mozilla/5.0 (Linux; Android 10; Pixel 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Mobile Safari/537.36',
  },
  shouldOpenMainDevTool: false,
  shouldOpenPopupDevTool: false,
  shouldOpenHelpDevTool: false,
  shouldOpenActionsBarDevTool: false,
  shouldOpenAutosuggestDevTool: false,
  shouldOpenInterpreterDevTool: false,
  shouldShowTotalMemory: false,
  shouldUseDebugWindowsHelperExe: false,
  shouldMiniToNormalAtCenter: true,
  memoryMultiplierMac: 1.8,
  memoryMultiplierWin: 1.9,
  memoryMultiplierLinux: 1,
  memoryOffsetMac: -80,
  memoryOffsetWin: -100,
  memoryOffsetLinux: 0,
};

if (SYSTEM_CONFIG.interpreterEnabled) {
  SYSTEM_CONFIG.platforms = [
    SYSTEM_CONFIG.openInterpreterPlatform,
    ...SYSTEM_CONFIG.platforms,
  ];
}
if (SYSTEM_CONFIG.operationsEnabled) {
  SYSTEM_CONFIG.platforms = [
    SYSTEM_CONFIG.localBasePlatform,
    ...SYSTEM_CONFIG.platforms,
  ];
}
